### ISSUE TITLE
Previously ran tests may pollute global variables/state

### ISSUE THREAD

**Issue by OlliV** [zeit/best#5]
**util/util.js**
```js
const a = [];

module.exports = () => a.push('t');
```

**test1.js**
```js
const fn = require('./util/util.js');

module.exports = async () => fn();
```

**test2.js**
```js
const fn = require('./util/util.js');

module.exports = async () => fn();
```

Guess what's in `a`.

It's not a bug, it's a feature. But it's regardless a bit unintuitive feature.

**Comment by OlliV** [comment]
I was writing a `setup()` function for my tests but that doesn't actually solve the issue because the tests are executed concurrently.

**Comment by OlliV** [comment]
I solved this for now in the following way:
```
#!/bin/bash

for file in $PWD/test/*.js
do
    best -v -I "$file"
done
```

and `"test": "./test/run.sh"` in the `package.json` file.

**Comment by nkzawa** [comment]
@OlliV I think `const fn = require('./util/file1.js');` is `const fn = require('./util/util.js');`? then I think it's expected.

**Comment by OlliV** [comment]
@nkzawa oh, right, fixed the typo.

**Comment by OlliV** [comment]
@nkzawa and yeah, it's expected but it might break some tests where a completely initialized state is expected. For example in my case, I'm mocking Cosmos DB so the collections are stored in global variables.

**Comment by Qix-** [comment]
I wrote `best` with the intent that you'd build up/tear down in each test case. Writing a utility function for common setup/tear down and `await`-ing it or something is probably the best way.

**Comment by Qix-** [comment]
Also,

> tests are executed concurrently

They aren't :o Just checked. `await` in loop, which is on purpose here.

**Comment by Qix-** [comment]
This is traditionally what [`import-fresh`](https://github.com/sindresorhus/import-fresh)-like utilities are for. The only way to guarantee that globals aren't messed with is to provide a sandboxed environment using `vm` or `fork`.

**Comment by Qix-** [comment]
Is there anything actionable here? I'm tempted to close this simply because I don't think any automatic cleanup makes sense.
